name: PenumbraiOS
options:
  bundleIdPrefix: com.vivianphung
packages:
  SwiftProtobuf:
    url: https://github.com/apple/swift-protobuf.git
    from: 1.20.3
  GRPC:
    url: https://github.com/grpc/grpc-swift.git
    from: 1.13.0
  VivUIExtensions:
    url: https://github.com/VPhung24/VivUIExtensions.git
    from: 1.0.1
targets:
  ### PenumbraiOS App
  PenumbraiOS:
    name: PenumbraiOS
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: "PenumbraiOS"
        name: "PenumbraiOS"
      - path: "README.md"
        buildPhase: none
      - path: "CHANGELOG.md"
        buildPhase: none
      - path: "project.yml"
        buildPhase: none
      - path: ".swiftlint.yml"
        buildPhase: none
      - path: "Info.plist"
        buildPhase: none
    info:
      path: Info.plist
      properties:
        UILaunchScreen:
          UIColorName: LaunchBackground
          UIImageName: AppIcon
        CFBundleShortVersionString: "1"
        CFBundleVersion: "1.0"
        ITSAppUsesNonExemptEncryption: false
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIViewControllerBasedStatusBarAppearance: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: PenumbraiOSUITests
          randomExecutionOrder: true
        - name: PenumbraiOSProtosTests
          randomExecutionOrder: true
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1 # iphone only
        PRODUCT_BUNDLE_IDENTIFIER: com.vivianphung.PenumbraiOS
        DEVELOPMENT_TEAM: FG655QY4XD
        SWIFT_VERSION: 5.2
      debug:
      release:
    dependencies:
      - target: PenumbraiOSProtos
      - package: VivUIExtensions
    postCompileScripts:
      - script: /opt/homebrew/bin/swiftlint
        name: Run SwiftLint
        basedOnDependencyAnalysis: false

  ### PenumbraiOSUITests (will use for fastlane)

  PenumbraiOSUITests:
    name: PenumbraiOSUITests
    type: bundle.ui-testing
    scheme: {}
    dependencies:
      - target: PenumbraiOS
    deploymentTarget: "14.0"
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vivianphung.PenumbraiOSUITests
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: FG655QY4XD
        SWIFT_VERSION: 5.2
    sources: [PenumbraiOSUITests]
    postCompileScripts:
      - script: /opt/homebrew/bin/swiftlint
        name: Run SwiftLint
        basedOnDependencyAnalysis: false

  ### PenumbraiOSProtos framework

  PenumbraiOSProtos:
    name: PenumbraiOSProtos
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - path: "PenumbraiOSProtos"
        name: "PenumbraiOSProtos"
      - path: "tools"
        name: "tools"
    dependencies:
      - package: SwiftProtobuf
      - package: GRPC
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: PenumbraiOSProtosTests
          randomExecutionOrder: true
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vivianphung.PenumbraiOSProtos
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: FG655QY4XD
        SWIFT_VERSION: 5.2
    postCompileScripts:
      - script: /opt/homebrew/bin/swiftlint
        name: Run SwiftLint
        basedOnDependencyAnalysis: false
    gith:
      - script: tools/scripts/generateProtos.sh
        name: My Script

  ### PenumbraiOSProtosTests

  PenumbraiOSProtosTests:
    name: PenumbraiOSProtosTests
    type: bundle.unit-test
    dependencies:
      - target: PenumbraiOSProtos
    deploymentTarget: "14.0"
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vivianphung.PenumbraiOSProtosTests
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: FG655QY4XD
        SWIFT_VERSION: 5.2
    scheme: {}
    sources: [PenumbraiOSProtosTests]
    postCompileScripts:
      - script: /opt/homebrew/bin/swiftlint
        name: Run SwiftLint
        basedOnDependencyAnalysis: false
